#!/usr/bin/env zsh
# need to have 'eval "$(direnv hook zsh)"' in ~/.zshrc, otherwise this will not work

if [ -z "$1" ]; then
echo "Usage: unsolve <output_folder>"
return 1
fi

if [ ! -d "src/$1" ]; then
echo "Error: \"$1\" does not exist"
return 1
fi

rm -r "src/$1" || exit 1
echo "Removed \"$1\""
